spring.application.name=progetto-personale-siw

#==================================
# = Datasource
#================================== 
spring.jpa.database=POSTGRESQL     
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.hibernate.ddl-auto=create 
spring.jpa.properties.hibernate.format_sql=true   
# riferita a riga sopta AGGIUNGI questa (formatta le query)
#nella riga sopra sto dicendo che il database(e le tabelle) deve essere creato ex-novo
#(rimuovendo tabelle se esistono)
#per creare tabelle creo un sql in application properties(questo file)
spring.datasource.driver-class-name=org.postgresql.Driver
 #per comunicare con il dbms dovrai usare questa classe(riga sopra)
spring.datasource.url=jdbc:postgresql://localhost:5432/palestraprogetto
 #specifica dove si trova il dbms(in questo caso si trova sul mio pc, localhost,in ascolto sulla porta 5432,
 #il database si chiama movie(creato da noi))                                                  (riga sopra)
spring.datasource.username=postgres
spring.datasource.password=postgres
 #quando parliamo con dbms dobbiamo accedere con username e password
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#==================================
# = Web server
#==================================
server.port=8080
#==================================
# = Thymeleaf configurations             (sotto)
#==================================
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false
#spring.thymeleaf.enabled=true
spring.thymeleaf.encoding=UTF-8




